<!DOCTYPE html>
<html>
    <!-- Head of the document -->
    <head>
        <meta charset="UTF-8">
        <title>Tondova hra</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <link rel="stylesheet" type="text/css" href="style.css?v=1">
        <!-- Icons -->
        <!-- Generated by: http://realfavicongenerator.net/ -->            
            <link rel="apple-touch-icon" sizes="180x180" href="img/icons/apple-touch-icon.png">
            <link rel="icon" type="image/png" href="img/icons/favicon-32x32.png" sizes="32x32">
            <link rel="icon" type="image/png" href="img/icons/favicon-16x16.png" sizes="16x16">
            <link rel="manifest" href="img/icons/manifest.json">
            <link rel="mask-icon" href="img/icons/safari-pinned-tab.svg" color="#5bbad5">
            <link rel="shortcut icon" href="img/icons/favicon.ico">
            <meta name="msapplication-config" content="img/icons/browserconfig.xml">
            <meta name="theme-color" content="#ffffff">


    </head>
    
    <!-- Body of the document -->
    <body>
        <!-- script for no JS -->
        <script>
            document.body.className="js";
        </script>
        
        <!--_____________Page block_____________-->
        <div id="block">
            <!-- Header with navigation -->
            <div id="header">
                <h1><a href="./">Tondova hra</a></h1>
                <!-- navigation -->
                <ul>
                    <li><a  id="navLogin" href="#login">Log In / Sign Up</a></li>
                    <li><a id="navMyAccount"  href="#account" class="nav-hidden">My account</a></li>
                    <li><a id="navAbout" href="#about">About game</a></li>
                    <li><a id="navBest" href="#best">Best players</a></li>
                </ul>
                <div class='clear'></div>
            </div> <!-- end of header -->
            
            <div id="blank"></div> <!-- empty page -->
            
            <!-- Log in page -->
            <div id="login" class="hide">
                <h2><a href="#signup" class="noActive" id="switchSignup">Sign Up / </a>Log In</h2>
                <!-- Log in form -->
                <form class="loginForm" id="loginForm">
                    <label>User name: <input type="text" name="username" data-required="required"></label>
                    <label>Password: <input type="password" name="password" data-required="required"></label>
                    <input type="submit" name="submitLogin" value="Log In" class="button">
                    <p><a href="#signup">Create a new account.</a></p>
                    <div class="clear"></div>
                </form>                
            </div>
            
            <!-- Sign up page -->
            <div id="signup" class="hide">
                <h2>Sign Up<a href="#login" class="noActive" id="switchLogin"> / Log In</a></h2>
                <!-- sign up form -->
                <form class="loginForm" id="signupForm">
                    <label>Your name: <input type="text" name="name" data-required="required"></label>
                    <label>User name: <input type="text" name="username" data-required="required"></label>
                    <label>Password: <input type="password" name="password" data-required="required"></label>
                    <label>Repeat password: <input type="password" name="password2" data-required="required"></label>
                    <a id="showMoreDetails">I want to give you more details</a>
                    <fieldset id="moreDetails" class="hide">
                        <legend id="moreDetailsLegend">These inputs are not required</legend>
                        <label>Email: <input type="email" name="email" id="email-input"></label>
                        <div id="email-result" class="clear"></div>
                        <?php include "includes/moreDetails.php";?>
                    </fieldset>
                    <input type="submit" name="submitLogin" value="Sign Up" class="button">
                    <div class="clear"></div>
                </form>
            </div>
            
            <!-- About game page -->
            <div id="about"  class="hide">
                <?php  include "includes/aboutGame.php" ?>   
            </div>
            
            <!-- About game page -->
            <div id="best"  class="hide">
                <?php  include "includes/bestPlayers.php" ?>
            </div>
            
            <!-- My Account page -->
            <div id="account" class="hide">
                <h2>My Account</h2>
                <p>Welcome, <b id="accountUsername"></b> have a fun.</p>
                <p>Your best result is: <b id="accountMeters"></b></p>
                <p><a href="" id="account-logout" class="button">Logout</a></p>
            </div>
            
            <!-- Game field -->
            <div id="gameField">
                <!-- Game page -->
                <div id="gamePage">
                    <canvas id="canvasGame"></canvas>
                    <!-- Top labels -->
                    <div id="gameLabelLeft" class="gameTopLabels">
                        Coins: <span id="gameCollectedCoins"></span>
                        <span id="gameMetres"></span>
                    </div>
                    <div id="gameLabelRight" class="gameTopLabels">
                        <span id="gamePlayPause" class="button">Pause</span>
                        <!--<span id="gameFullScreen">Full Screen</span>-->
                    </div>
                    <div id="gameLives"></div>
                    
                    <!-- Game controls for touch screens -->
                    <div id="gameControlLeft" class="gameControls"></div>
                    <div id="gameControlRight" class="gameControls"></div>
                </div>
                
                <!-- Default game page -->
                <div id="gameDefaultPage">
                    <div class="cover">
                        <div id="gameDefaultStartButton" class="button">
                            Start Game
                        </div>
                    </div>
                </div>  
                
                <!-- page for the start of the game -->
                <div id="gameStartPage">
                    <div class="cover">
                        <!-- Field for buying extra balls -->
                        <div id="gameBuyingBallsField" class="left">
                            <div id="gameBuyingBuyButton">
                                <div></div>
                                <div id="gameBuyingPrice">100 $</div>
                            </div>
                            <div class="gameBuyingBallUser">
                                You have: 
                            <div id="gameBuyingCoinsNumber">10 coins</div>
                            <div id="gameBuyingBallsNumber">2 balls</div>
                            </div>                            
                        </div>
                        
                        <!-- start game button -->
                        <div id="gameStartPlayButton" class="button right">Play</div>
                    </div>
                </div>
                
                <!-- Page for the end of the game -->
                <div id="gameEndPage">
                    <div class="cover">
                        <!-- score field -->
                        <div class="left">
                            <div id="gameEndCoins">Coins: +254 (total: 500)</div>
                            <div id="gameEndMeters">Meters: 55 (best: 600)</div>
                            <div id="gameEndLevel">Level: 2 (previous best: 2)</div>
                        </div>
                        
                        <!-- play again button -->
                        <div class="right">
                            <div id="gameEndPlayButton" class="button">Play Again</div>
                        </div>
                    </div>      
                </div>
            </div> <!-- end game field -->
            
            <!-- Footer -->
            <div id="footer">
                <a href="https://www.tondakozak.cz/" title="Tonda Kozák's personal page">&copy; Tonda Kozák, 2016</a>
            </div>
            
        </div><!-- end of the block -->
        
        
        <!-- JavaScript -->
        <script src="script/other_functions.js"></script>
        <script src="script/best_players.js"></script>
        <script src="script/pages_class.js"></script>
        <script src="script/user_class.js"></script>
        <script src="script/game_class.js"></script>
        <script src="script/main.js"></script>
    </body>
</html>
